//
// Created by 17333 on 25-6-26.
//

#ifndef BSP_POWER_H
#define BSP_POWER_H

#include <bsp.h>

//#define VBAT_FUNC

#define BSP_VOL_WORK 1
#define BSP_VOL_DEBUG 0
#define BSP_CUR_WORK 1
#define BSP_CUR_DEBUG 0


#define ELVSS_ENABLE() HAL_GPIO_WritePin(ELVSS_EN_GPIO_Port, ELVSS_EN_Pin, GPIO_PIN_RESET)
#define ELVDD_ENABLE() HAL_GPIO_WritePin(ELVDD_EN_GPIO_Port, ELVDD_EN_Pin, GPIO_PIN_SET)
#define VCC_ENABLE() HAL_GPIO_WritePin(VCC_EN_GPIO_Port, VCC_EN_Pin, GPIO_PIN_SET)
#define IOVCC_ENABLE() HAL_GPIO_WritePin(IOVCC_EN_GPIO_Port, IOVCC_EN_Pin, GPIO_PIN_SET)
#define SHUTDOWN_ENABLE() HAL_GPIO_WritePin(SHUTDOWN_EN_GPIO_Port, SHUTDOWN, GPIO_PIN_RESET)

#define ELVSS_DISABLE() HAL_GPIO_WritePin(ELVSS_EN_GPIO_Port, ELVSS_EN_Pin, GPIO_PIN_SET)
#define ELVDD_DISABLE() HAL_GPIO_WritePin(ELVDD_EN_GPIO_Port, ELVDD_EN_Pin, GPIO_PIN_RESET)
#define VCC_DISABLE() HAL_GPIO_WritePin(VCC_EN_GPIO_Port, VCC_EN_Pin, GPIO_PIN_RESET)
#define IOVCC_DISABLE() HAL_GPIO_WritePin(IOVCC_EN_GPIO_Port, IOVCC_EN_Pin, GPIO_PIN_RESET)
#define SHUTDOWN_DISABLE() HAL_GPIO_WritePin(SHUTDOWN_EN_GPIO_Port, SHUTDOWN, GPIO_PIN_SET)

#ifdef VBAT_FUNC
#define VBAT_ENABLE() HAL_GPIO_WritePin(VBAT_EN_GPIO_Port, VBAT_EN_Pin, GPIO_PIN_SET)
#define VBAT_DISABLE() HAL_GPIO_WritePin(VBAT_EN_GPIO_Port, VBAT_EN_Pin, GPIO_PIN_RESET)
#else
#define VBAT_ENABLE() 
#define VBAT_DISABLE() 
#endif
#endif //BSP_POWER_H
